# Generated by Django 6.0.3 on 2026-06-28 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_customuser_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudRolDueño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(help_text='Explica por qué deseas registrar tu cancha en GoSport.', verbose_name='Motivo de la solicitud')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de respuesta')),
                ('notas_admin', models.TextField(blank=True, help_text='Motivo de aprobación o rechazo (visible para el usuario).', verbose_name='Notas del administrador')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_rol', to=settings.AUTH_USER_MODEL, verbose_name='Usuario solicitante')),
            ],
            options={
                'verbose_name': 'Solicitud de Rol Dueño',
                'verbose_name_plural': 'Solicitudes de Rol Dueño',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
