# Generated by Django 6.0.3 on 2026-03-22 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0002_initial'),
        ('negocio', '0003_reserva_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='canchas',
            field=models.ManyToManyField(blank=True, related_name='torneos_list', to='canchas.cancha'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='deporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='canchas.deporte'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='torneo',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
