# Generated by Django 6.0.3 on 2026-03-24 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0003_alter_disponibilidad_unique_together_and_more'),
        ('negocio', '0004_torneo_canchas_torneo_deporte_torneo_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='fixture_generado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='torneo',
            name='formato',
            field=models.CharField(choices=[('LIGA', 'Liga (Todos contra todos)'), ('ELIMINACION', 'Eliminación Directa')], default='LIGA', max_length=20),
        ),
        migrations.AddField(
            model_name='torneo',
            name='max_equipos',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles_local', models.PositiveIntegerField(default=0)),
                ('goles_visitante', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('JUGADO', 'Jugado')], default='PENDIENTE', max_length=20)),
                ('jornada', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('cancha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos', to='canchas.cancha')),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='negocio.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='negocio.equipo')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='negocio.torneo')),
            ],
            options={
                'ordering': ['jornada', 'fecha'],
            },
        ),
        migrations.CreateModel(
            name='PosicionEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField(default=0)),
                ('partidos_jugados', models.PositiveIntegerField(default=0)),
                ('partidos_ganados', models.PositiveIntegerField(default=0)),
                ('partidos_empatados', models.PositiveIntegerField(default=0)),
                ('partidos_perdidos', models.PositiveIntegerField(default=0)),
                ('goles_favor', models.PositiveIntegerField(default=0)),
                ('goles_contra', models.PositiveIntegerField(default=0)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posiciones_torneo', to='negocio.equipo')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posiciones', to='negocio.torneo')),
            ],
            options={
                'ordering': ['-puntos', '-partidos_ganados', '-goles_favor'],
                'unique_together': {('torneo', 'equipo')},
            },
        ),
    ]
