# Generated by Django 6.0.3 on 2026-04-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0005_torneo_fixture_generado_torneo_formato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='referencia_pago',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='wompi_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
