# Generated by Django 6.0.3 on 2026-04-07 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0006_factura_referencia_pago_factura_wompi_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='precio_inscripcion',
            field=models.DecimalField(decimal_places=2, default=50000.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PUBLICADO', 'Publicado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20),
        ),
    ]
