# Generated by Django 6.0.3 on 2026-04-07 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0007_torneo_precio_inscripcion_alter_torneo_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudModificacionTorneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_cambio', models.TextField(help_text='Explique detalladamente qué cambios necesita hacer en el torneo.')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_modificacion', to='negocio.torneo')),
            ],
        ),
    ]
