# Generated by Django 6.0.3 on 2026-06-27 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0005_cancha_ciudad'),
        ('negocio', '0008_solicitudmodificaciontorneo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromocionTorneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_promocional', models.TextField(help_text='Texto descriptivo para la publicidad del torneo.')),
                ('imagen_promocional', models.ImageField(blank=True, null=True, upload_to='promociones/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='canchas.cancha')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='negocio.torneo')),
            ],
        ),
    ]
