# Generated by Django 6.0.3 on 2026-06-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0009_promociontorneo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='hora_fin',
            field=models.TimeField(blank=True, help_text='Hora de fin', null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora',
            field=models.TimeField(help_text='Hora de inicio'),
        ),
    ]
