# Generated by Django 6.0.3 on 2026-03-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidad',
            name='dia_semana',
            field=models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='disponibilidad',
            unique_together={('cancha', 'dia_semana', 'hora_inicio', 'hora_fin')},
        ),
        migrations.RemoveField(
            model_name='disponibilidad',
            name='dia',
        ),
    ]
