# Generated by Django 6.0.3 on 2026-04-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0004_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='ciudad',
            field=models.CharField(default='Bogotá', max_length=100),
        ),
    ]
